import type { AtmOperatorFeeRule, CardIssuerTravelRule, CountryAtmFeeRule } from '@/services/atm/feeIntelligenceSeed';

// Second-pass research seed. These entries are intentionally conservative: they
// support ranking, warnings and confidence prompts, not absolute guarantees.
// The app should combine these with live Google/OSM operator matches and user
// reports before showing high-confidence recommendations.

export const expandedCountryAtmFeeSeed: CountryAtmFeeRule[] = [
  {
    countryCode: 'FR',
    countryName: 'France',
    defaultOutcome: 'likely-free',
    defaultTypicalFeeLocal: 'Bank ATMs are often a good first choice; independent/tourist ATMs still need caution',
    defaultConfidence: 'low',
    notes: 'France should be researched around BNP Paribas, Crédit Agricole, Société Générale, Banque Populaire/Caisse d’Epargne, LCL and CIC. Global ATM Alliance data suggests BNP Paribas is strategically important for some foreign bank customers, but this does not automatically prove no surcharge for UK challenger cards.',
    sources: [
      { type: 'reference', label: 'Global ATM Alliance lists BNP Paribas coverage in France for participating banks', url: 'https://en.wikipedia.org/wiki/Global_ATM_Alliance' },
      { type: 'research-note', label: 'Needs UK-card-specific ATM-owner surcharge verification' },
    ],
  },
  {
    countryCode: 'IT',
    countryName: 'Italy',
    defaultOutcome: 'mixed',
    defaultTypicalFeeLocal: 'Bank ATMs can be reasonable; tourist/independent ATMs can surcharge',
    defaultConfidence: 'low',
    notes: 'Research around UniCredit, Intesa Sanpaolo, BNL, Poste Italiane, Banco BPM and Euronet. Global ATM Alliance points to BNL d’Italia as relevant for some international customers, but UK challenger cards still need Transvert/user confirmation.',
    sources: [
      { type: 'reference', label: 'Global ATM Alliance lists BNL d’Italia coverage in Italy for participating banks', url: 'https://en.wikipedia.org/wiki/Global_ATM_Alliance' },
      { type: 'research-note', label: 'Needs operator/card-specific surcharge data' },
    ],
  },
  {
    countryCode: 'DE',
    countryName: 'Germany',
    defaultOutcome: 'mixed',
    defaultTypicalFeeLocal: 'ATM owner fees can be displayed before withdrawal; bank network/group matters',
    defaultConfidence: 'medium',
    notes: 'German ATM fees vary by network and group. Important operators/networks: Sparkasse, Volksbank/Raiffeisenbank, Deutsche Bank, Commerzbank, Postbank, Cash Group, CashPool and Euronet. For Germany, app should warn strongly to read the on-screen surcharge before acceptance.',
    sources: [
      { type: 'reference', label: 'ATM usage fee overview notes German surcharges commonly displayed before withdrawal and network groups matter', url: 'https://en.wikipedia.org/wiki/ATM_usage_fees' },
      { type: 'reference', label: 'Global ATM Alliance lists Deutsche Bank Germany for participating banks', url: 'https://en.wikipedia.org/wiki/Global_ATM_Alliance' },
    ],
  },
  {
    countryCode: 'NL',
    countryName: 'Netherlands',
    defaultOutcome: 'likely-free',
    defaultTypicalFeeLocal: 'Bank/network ATMs are generally better than tourist machines; still check screen',
    defaultConfidence: 'low',
    notes: 'Research Geldmaat, ABN AMRO, ING and Rabobank. Netherlands likely less painful than Spain tourist resorts, but exact foreign-card surcharge data still needs validation.',
    sources: [{ type: 'research-note', label: 'Needs country/operator-specific source sweep' }],
  },
  {
    countryCode: 'IE',
    countryName: 'Ireland',
    defaultOutcome: 'likely-free',
    defaultTypicalFeeLocal: 'Bank ATMs often appear low-risk; independent/tourist ATMs need caution',
    defaultConfidence: 'low',
    notes: 'Research Bank of Ireland, AIB, Permanent TSB, Ulster legacy locations and Euronet. UK cards may still have issuer fees depending on card.',
    sources: [{ type: 'research-note', label: 'Needs country/operator-specific source sweep' }],
  },
  {
    countryCode: 'US',
    countryName: 'United States',
    defaultOutcome: 'known-fee',
    defaultTypicalFeeLocal: 'ATM owner fee often applies, commonly several dollars',
    defaultConfidence: 'medium',
    notes: 'US is generally surcharge-heavy for foreign cards. Useful networks/operators: Allpoint, MoneyPass, Bank of America, Chase, Wells Fargo, Citi, PNC. Exact card fee depends heavily on the traveller’s home card and network access.',
    sources: [
      { type: 'reference', label: 'ATM usage fee overview documents operator/foreign ATM fees as a normal concept', url: 'https://en.wikipedia.org/wiki/ATM_usage_fees' },
      { type: 'reference', label: 'Global ATM Alliance covers Bank of America for participating customers', url: 'https://en.wikipedia.org/wiki/Global_ATM_Alliance' },
    ],
  },
  {
    countryCode: 'CA',
    countryName: 'Canada',
    defaultOutcome: 'mixed',
    defaultTypicalFeeLocal: 'ATM access fee may apply; partner network matters',
    defaultConfidence: 'low',
    notes: 'Research Scotiabank, RBC, TD, BMO, CIBC. Global ATM Alliance is relevant because Scotiabank participates for some foreign customers.',
    sources: [
      { type: 'reference', label: 'Global ATM Alliance lists Canada coverage through Scotiabank for participating banks', url: 'https://en.wikipedia.org/wiki/Global_ATM_Alliance' },
    ],
  },
  {
    countryCode: 'MA',
    countryName: 'Morocco',
    defaultOutcome: 'mixed',
    defaultTypicalFeeLocal: 'Likely varies by bank/operator; BNP Paribas affiliate coverage may matter for some cards',
    defaultConfidence: 'low',
    notes: 'Research BMCI/BNP Paribas, Attijariwafa, Banque Populaire, CIH, Crédit Agricole du Maroc. Tourist areas need extra caution.',
    sources: [
      { type: 'reference', label: 'Global ATM Alliance lists BNP Paribas affiliate coverage in Morocco for participating banks', url: 'https://en.wikipedia.org/wiki/Global_ATM_Alliance' },
    ],
  },
  {
    countryCode: 'HR',
    countryName: 'Croatia',
    defaultOutcome: 'mixed',
    defaultTypicalFeeLocal: 'Tourist area ATMs may surcharge; bank ATMs should be prioritised over independent operators',
    defaultConfidence: 'low',
    notes: 'Research Zagrebačka banka, PBZ, Erste, OTP, Addiko and Euronet. Croatia is a strong holiday-market priority.',
    sources: [{ type: 'research-note', label: 'Needs country/operator-specific source sweep' }],
  },
  {
    countryCode: 'AE',
    countryName: 'United Arab Emirates',
    defaultOutcome: 'mixed',
    defaultTypicalFeeLocal: 'ATM fees and DCC can vary; hotel/mall tourist ATMs need caution',
    defaultConfidence: 'low',
    notes: 'Research Emirates NBD, ADCB, FAB, Mashreq, Dubai Islamic Bank. Dubai is a high-priority UK travel corridor.',
    sources: [{ type: 'research-note', label: 'Needs country/operator-specific source sweep' }],
  },
];

export const expandedOperatorAtmFeeSeed: AtmOperatorFeeRule[] = [
  {
    id: 'fr-bnp-paribas',
    countryCode: 'FR',
    countryName: 'France',
    operator: 'BNP Paribas',
    aliases: ['BNP', 'BNP Paribas ATM'],
    outcome: 'likely-free',
    typicalFeeLocal: 'Potentially favourable for some participating foreign-bank customers; UK challenger cards still need confirmation',
    cardNotes: 'Good initial rank in France but do not promise free for Starling/Revolut without reports.',
    dccWarning: true,
    confidence: 'low',
    lastChecked: '2026-06-27',
    sources: [{ type: 'reference', label: 'Global ATM Alliance lists BNP Paribas in France', url: 'https://en.wikipedia.org/wiki/Global_ATM_Alliance' }],
    notes: 'Ask for post-withdrawal report to rapidly validate UK card outcomes.',
  },
  {
    id: 'it-bnl-ditalia',
    countryCode: 'IT',
    countryName: 'Italy',
    operator: 'BNL d’Italia',
    aliases: ['BNL', 'BNL Gruppo BNP Paribas', 'Banca Nazionale del Lavoro'],
    outcome: 'likely-free',
    typicalFeeLocal: 'Potentially favourable for some participating foreign-bank customers; UK challenger cards still need confirmation',
    cardNotes: 'Good initial rank in Italy but Transvert should request report.',
    dccWarning: true,
    confidence: 'low',
    lastChecked: '2026-06-27',
    sources: [{ type: 'reference', label: 'Global ATM Alliance lists BNL d’Italia in Italy', url: 'https://en.wikipedia.org/wiki/Global_ATM_Alliance' }],
    notes: 'Potentially useful “try first” bank ATM in Italy, not a guarantee.',
  },
  {
    id: 'de-deutsche-bank',
    countryCode: 'DE',
    countryName: 'Germany',
    operator: 'Deutsche Bank',
    aliases: ['Deutsche Bank ATM'],
    outcome: 'likely-free',
    typicalFeeLocal: 'Potentially favourable for some participating foreign-bank customers; general foreign-card fees still need screen confirmation',
    cardNotes: 'May be useful for Global ATM Alliance customers; Starling/Revolut need user reports.',
    dccWarning: true,
    confidence: 'low',
    lastChecked: '2026-06-27',
    sources: [{ type: 'reference', label: 'Global ATM Alliance lists Deutsche Bank in Germany and Spain', url: 'https://en.wikipedia.org/wiki/Global_ATM_Alliance' }],
    notes: 'Rank above unknown independents, below confirmed local free reports.',
  },
  {
    id: 'es-deutsche-bank',
    countryCode: 'ES',
    countryName: 'Spain',
    operator: 'Deutsche Bank',
    aliases: ['Deutsche Bank Spain', 'Deutsche Bank ATM'],
    outcome: 'likely-free',
    typicalFeeLocal: 'Potentially favourable for some participating foreign-bank customers; UK challenger cards need reports',
    cardNotes: 'Good Spain candidate to test alongside Unicaja/BBVA if present nearby.',
    dccWarning: true,
    confidence: 'low',
    lastChecked: '2026-06-27',
    sources: [{ type: 'reference', label: 'Global ATM Alliance lists Deutsche Bank in Spain for participating banks', url: 'https://en.wikipedia.org/wiki/Global_ATM_Alliance' }],
    notes: 'Possible “try first” in Spain, but not enough for confirmed-free label.',
  },
  {
    id: 'de-sparkasse',
    countryCode: 'DE',
    countryName: 'Germany',
    operator: 'Sparkasse',
    aliases: ['Sparkassen', 'Savings Bank ATM'],
    outcome: 'mixed',
    typicalFeeLocal: 'German ATM owner fees can range around €1.95–€5+ and must be shown before withdrawal',
    cardNotes: 'Warn UK travellers to read the on-screen fee before confirming.',
    dccWarning: true,
    confidence: 'medium',
    lastChecked: '2026-06-27',
    sources: [{ type: 'reference', label: 'ATM usage fee overview notes German surcharges from about €1.95 to €5+ displayed before withdrawal', url: 'https://en.wikipedia.org/wiki/ATM_usage_fees' }],
    notes: 'Do not assume free for foreign cards.',
  },
  {
    id: 'de-cash-group',
    countryCode: 'DE',
    countryName: 'Germany',
    operator: 'Cash Group bank ATM',
    aliases: ['Commerzbank', 'Deutsche Bank', 'HypoVereinsbank', 'Postbank', 'Cash Group'],
    outcome: 'mixed',
    typicalFeeLocal: 'Network benefits are card/account-specific; foreign-card users need screen confirmation',
    cardNotes: 'Potentially better than independents, but not automatically free for UK cards.',
    dccWarning: true,
    confidence: 'low',
    lastChecked: '2026-06-27',
    sources: [{ type: 'reference', label: 'ATM usage fee overview notes Germany has bank groups that waive or reduce fees for members', url: 'https://en.wikipedia.org/wiki/ATM_usage_fees' }],
    notes: 'Candidate for better ranking once reports exist.',
  },
  {
    id: 'global-travelex',
    countryCode: 'GLOBAL',
    countryName: 'Global tourist areas',
    operator: 'Travelex',
    aliases: ['Travelex ATM', 'Travelex cash machine'],
    outcome: 'avoid',
    typicalFeeLocal: 'Tourist/FX operator ATM: likely higher fee or poorer conversion prompt',
    cardNotes: 'Avoid for Starling/Revolut/Chase/Wise where a bank ATM alternative exists.',
    dccWarning: true,
    confidence: 'medium',
    lastChecked: '2026-06-27',
    sources: [{ type: 'research-note', label: 'Classed as high-risk FX/tourist operator; needs country-specific fee confirmation' }],
    notes: 'Rank near Euronet until proven otherwise.',
  },
  {
    id: 'global-cardtronics',
    countryCode: 'GLOBAL',
    countryName: 'Global tourist areas',
    operator: 'Cardtronics',
    aliases: ['Cardtronics ATM', 'NCR Atleos'],
    outcome: 'fee-likely',
    typicalFeeLocal: 'Independent operator: fee likely unless local rule/report says otherwise',
    cardNotes: 'Warn and rank below bank-owned ATMs.',
    dccWarning: true,
    confidence: 'medium',
    lastChecked: '2026-06-27',
    sources: [{ type: 'research-note', label: 'Independent ATM operator pattern' }],
    notes: 'Country-specific user reports should override this seed.',
  },
  {
    id: 'global-cashzone',
    countryCode: 'GLOBAL',
    countryName: 'Global tourist areas',
    operator: 'Cashzone',
    aliases: ['Cashzone ATM'],
    outcome: 'fee-likely',
    typicalFeeLocal: 'Independent operator: fee likely unless local report says otherwise',
    cardNotes: 'Warn and rank below bank-owned ATMs.',
    dccWarning: true,
    confidence: 'medium',
    lastChecked: '2026-06-27',
    sources: [{ type: 'research-note', label: 'Independent ATM operator pattern' }],
    notes: 'Useful UK/EU independent-operator seed.',
  },
  {
    id: 'gr-euronet',
    countryCode: 'GR',
    countryName: 'Greece',
    operator: 'Euronet',
    aliases: ['Euronet Greece', 'Euronet ATM'],
    outcome: 'avoid',
    typicalFeeLocal: 'Likely tourist-area surcharge; exact Greek fee needs confirmation',
    cardNotes: 'Avoid where a Greek bank ATM alternative exists.',
    dccWarning: true,
    confidence: 'medium',
    lastChecked: '2026-06-27',
    sources: [{ type: 'research-note', label: 'Global Euronet risk pattern applied to Greece' }],
    notes: 'High-priority validation target for Greek islands.',
  },
  {
    id: 'hr-euronet',
    countryCode: 'HR',
    countryName: 'Croatia',
    operator: 'Euronet',
    aliases: ['Euronet Croatia', 'Euronet ATM'],
    outcome: 'avoid',
    typicalFeeLocal: 'Likely tourist-area surcharge; exact Croatian fee needs confirmation',
    cardNotes: 'Avoid where a Croatian bank ATM alternative exists.',
    dccWarning: true,
    confidence: 'medium',
    lastChecked: '2026-06-27',
    sources: [{ type: 'research-note', label: 'Global Euronet risk pattern applied to Croatia' }],
    notes: 'High-priority validation target for Croatian coastal resorts.',
  },
];

export const expandedCardIssuerTravelSeed: CardIssuerTravelRule[] = [
  {
    id: 'uk-first-direct-debit',
    issuer: 'First Direct',
    cardName: 'Debit card',
    homeCountry: 'UK',
    fxMarkup: 'Reported no fees for paying abroad',
    atmWithdrawalRule: 'Reported no penalty for withdrawing cash abroad; ATM owner can still charge',
    networkRate: 'Card network route',
    confidence: 'medium',
    lastChecked: '2026-06-27',
    notes: 'Add as a strong UK travel-card option after official verification.',
    sources: [{ type: 'news', label: 'UK money press lists First Direct as no-fee abroad debit option' }],
  },
  {
    id: 'uk-santander-edge-debit',
    issuer: 'Santander UK',
    cardName: 'Edge current account debit card',
    homeCountry: 'UK',
    fxMarkup: 'Reported no fees overseas for qualifying Edge account customers',
    atmWithdrawalRule: 'Reported no Santander fee for overseas ATM withdrawals on Edge; account has conditions/monthly fee; ATM owner can still charge',
    networkRate: 'Card network route',
    confidence: 'medium',
    lastChecked: '2026-06-27',
    notes: 'Model separately from standard Santander UK debit cards.',
    sources: [{ type: 'news', label: 'UK money press lists Santander Edge as no-fee abroad with account conditions' }],
  },
  {
    id: 'uk-barclaycard-rewards',
    issuer: 'Barclaycard',
    cardName: 'Rewards credit card',
    homeCountry: 'UK',
    fxMarkup: 'No foreign spending fee reported',
    atmWithdrawalRule: 'No Barclaycard ATM withdrawal fee/interest if repaid by next statement reported; ATM owner can still charge',
    networkRate: 'Card network route',
    confidence: 'medium',
    lastChecked: '2026-06-27',
    notes: 'Credit-card cash use still needs careful user education; do not present as simple debit-card equivalent.',
    sources: [{ type: 'news', label: 'UK money press lists Barclaycard Rewards as travel-friendly card' }],
  },
  {
    id: 'uk-halifax-clarity',
    issuer: 'Halifax',
    cardName: 'Clarity credit card',
    homeCountry: 'UK',
    fxMarkup: 'No overseas spending fee reported',
    atmWithdrawalRule: 'No Halifax cash withdrawal fee reported, but interest on cash withdrawals can start immediately; ATM owner can still charge',
    networkRate: 'Card network route',
    confidence: 'medium',
    lastChecked: '2026-06-27',
    notes: 'Useful travel card but cash withdrawals need warning about interest.',
    sources: [{ type: 'news', label: 'UK money press lists Halifax Clarity as travel-friendly, with cash-interest caveat' }],
  },
  {
    id: 'uk-kroo-debit',
    issuer: 'Kroo Bank',
    cardName: 'Current account debit card',
    homeCountry: 'UK',
    fxMarkup: 'Reported fee-free overseas payments',
    atmWithdrawalRule: 'Reported overseas ATM withdrawals fee-free up to £200/month then 3%; ATM owner can still charge',
    networkRate: 'Card network route',
    confidence: 'medium',
    lastChecked: '2026-06-27',
    notes: 'Good candidate but allowance-limited.',
    sources: [{ type: 'news', label: 'UK money press reports Kroo overseas ATM allowance and 3% over-limit fee' }],
  },
  {
    id: 'uk-hsbc-global-money',
    issuer: 'HSBC UK',
    cardName: 'Global Money account card',
    homeCountry: 'UK',
    fxMarkup: 'Designed for multi-currency travel use',
    atmWithdrawalRule: 'Reported fee-free transactions/multi-currency withdrawals up to limits; ATM owner can still charge',
    networkRate: 'HSBC/card network multi-currency route',
    confidence: 'low',
    lastChecked: '2026-06-27',
    notes: 'Needs current official HSBC source. Distinguish from standard HSBC debit card fees.',
    sources: [{ type: 'news', label: 'UK/Ireland press reports HSBC Global Money as fee-free multi-currency option with withdrawal limits' }],
  },
];
